---
title: Forms Concepts
tutorial_title: Forms
status: editors-draft
order: 1
topic_order: 3
type: intro
---

## Overview

To create an accessible form you will need to provide:

- **[Descriptive labels](labels.html):** So that the user is in no doubt about what input they should provide and whether or not the field is mandatory;
- **[Clear instructions](instructions.html):** To ensure that the user is aware of indicators or formats they need to use to complete the form;
- **[Understandable structure](structure.html):** Especially where the form is presented to the user over several pages, or there are multiple form controls covered by one single question;
- **[Error prevention](error-prevention.html) or help with [error correction](error-messages.html):** To assure successful submission.

## Who benefits

Forms can be complex and difficult to use. Accessible forms are easier to complete for everyone, including people with disabilities

- **People using speech input assistive technology:** Can move the cursor into the fields they need to complete using voice commands.
- **People with shaky hands:** Can use the label as a larger clickable area for selecting small controls such as radio buttons and checkboxes.
- **People using screen readers:** Will have labels properly identified (including required fields and format restrictions) if labels and in-line instructions are correctly positioned and coded.

## Relationship to WCAG 2.0

Accessible forms are required by the following WCAG 2.0 Success Criterion:

- [Info and Relationships SC 1.3.1](http://www.w3.org/WAI/WCAG20/quickref/#qr-content-structure-separation-programmatic): Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text. (Level A);
- [Headings and Labels SC 2.4.6](http://www.w3.org/WAI/WCAG20/quickref/20120103/#navigation-mechanisms-descriptive): Headings and labels describe topic or purpose. (Level AA) ;
- [Labels or Instructions SC 3.3.2](http://www.w3.org/WAI/WCAG20/quickref/20120103/#minimize-error-cues): Labels or instructions are provided when content requires user input. (Level A);
- [Name, Role, Value SC 4.1.](http://www.w3.org/WAI/WCAG20/quickref/#qr-ensure-compat-rsv)2: For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies. (Level A)

How people with disabilities use the web (Diversity in Web Use - Design solutions - [navigating and finding content](http://www.w3.org/WAI/intro/people-use-web/browsing#navigation)).
